### ISSUE TITLE
ModuleNotFoundError: No module named 'PyamilySeq_Species'

### ISSUE THREAD

**Issue by ecampbell50** [NickJD/PyamilySeq#1]
Hi Nick,

Thanks for making a nice tool, I ran into a minor issue when running PyamilySeq for the first time:

```
Traceback (most recent call last):
  File "/users/emmet/.local/bin/PyamilySeq", line 5, in <module>
    from PyamilySeq.PyamilySeq import main
  File "/users/emmet/.local/lib/python3.10/site-packages/PyamilySeq/PyamilySeq.py", line 6, in <module>
    from PyamilySeq_Species import *
ModuleNotFoundError: No module named 'PyamilySeq_Species'
```

I fixed this by just putting a '.' in front of "PyamilySeq_Species" on line 6 and 14, as it appears on line 10.
Tool ran fine after this change!

Kind regards,
Emmet

**Comment by NickJD** [comment]
Hey.
Thanks @ecampbell50 - This was an oversight from development that I had forgotten to remove. I will issue a quick fix now and see if that resolves it for you.

Nick.

**Comment by NickJD** [comment]
I have pushed a new release to Github and PyPi - Please give it a try when you can.
https://github.com/NickJD/PyamilySeq/releases/tag/v0.5.1

**Comment by ecampbell50** [comment]
That worked! Thanks ☺️
