### ISSUE TITLE
Gene presence/absence file output as default

### ISSUE THREAD

**Issue by ecampbell50** [NickJD/PyamilySeq#2]
Hi Nick,

Could the gene presence/absence file (created with -gpa option) be output as default rather than not? To avoid running a whole job and forgetting to add it!

Kind regards,
Emmet

**Comment by NickJD** [comment]
Hi @ecampbell50. Thanks for another suggestion. This has been implemented now as default in v0.8.0 https://github.com/NickJD/PyamilySeq/releases/tag/v0.8.0
